CREATE ROLE probot;
ALTER ROLE probot WITH SUPERUSER
INHERIT
CREATEROLE
CREATEDB
LOGIN
NOREPLICATION
NOBYPASSRLS
PASSWORD 'probotpass';

CREATE DATABASE probot_db WITH TEMPLATE = template0 OWNER = postgres;
GRANT ALL ON DATABASE probot_db TO probot;
